version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0
  dotenv: anilanar/dotenv@volatile

jobs:
  build-and-publish-docker-image:
    environment:
      DOCKER_IMAGE: truongvn/trello-nestjs
      DOCKER_TAG: latest
    executor: docker/docker

    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - dotenv/source:
          path: .env
      - docker/build:
          cache_from: '$DOCKER_IMAGE/$DOCKER_TAG'
          extra_build_args: '--no-cache --target production'
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG

      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  deploy-digital-ocean-vps:
    executor: docker/docker
    steps:
      - add_ssh_keys
      - run: ssh-keyscan -H $DEPLOY_IP >> ~/.ssh/known_hosts
      - run: ssh -oStrictHostKeyChecking=no -v $DEPLOYED_USER@$DEPLOY_IP './scripts/deploy.sh'


workflows:
  docker-init:
    jobs:
      - build-and-publish-docker-image
      - deploy-digital-ocean-vps:
          requires:
            - build-and-publish-docker-image